homeassistant:
  name: "D'Anvers Edge"
  packages: !include_dir_named integrations

# Loads default set of integrations. Do not remove.
default_config:
mobile_app:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

zha:
  zigpy_config:
    ota:
      ikea_provider: true
  custom_quirks_path: custom_zha_quirks/

template: !include_dir_merge_list entities/templates
tts: !include_dir_merge_list entities/tts