alias: Arriving Home - EV Charging Notification
description: ""
triggers:
  - trigger: zone
    entity_id: device_tracker.pixel_8_4
    zone: zone.ev_trigger_zone
    event: enter
conditions:
  - type: is_connected
    condition: device
    device_id: 873ec1cb2655541330375c818cc941da
    entity_id: 406a41dc5528a0b8e891c5d2dfdaa777
    domain: binary_sensor
actions:
  - variables:
      cadix: "{{ states('sensor.cadixstraat_chargers') | int(0) }}"
      madras: "{{ states('sensor.madrasstraat_chargers') | int(0) }}"
      napels: "{{ states('sensor.napelsstraat_chargers') | int(0) }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ cadix + madras + napels > 0 }}"
        sequence:
          - action: notify.mobile_app_d_anvers_edge_beacon_8
            metadata: {}
            data:
              title: You can charge!
              message: |
                CADIX {{ cadix }} / MADRAS {{ madras }} / NAPELS {{ napels }}
              data:
                car_ui: true
                ttl: 0
                priority: high
                importance: high
    default:
      - action: notify.mobile_app_d_anvers_edge_beacon_8
        metadata: {}
        data:
          title: sorry :(
          message: No chargers free
          data:
            car_ui: true
            ttl: 0
            priority: high
            importance: high
mode: single